# Docs:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

name: Build Master

on:
  push:
    branches: [ master ]
    paths:
      - '**.js'
      - '**.yml'
      - 'test/**'

  # pull_request:
  #   branches: [ master ]
  #   paths:
  #     - '**.js'
  #     - '**.yml'
  #     - 'test/**'


defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ALEXA_SKILL_ID: ${{ secrets.ALEXA_SKILL_ID }}
  SLS_STAGE: prod

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm install

      - name: Deploy with Serverless
        run: serverless deploy -s $SLS_STAGE
